
name: rasterview
version: 1.5.1
summary: CUPS/PWG/Apple Raster File Viewer
description: |
  RasterView is a CUPS, PWG, and Apple raster file viewer.  It basically allows
  you to look at the raster data produced by any of the standard CUPS RIP filters
  (cgpdftoraster, imagetoraster, pdftoraster, and pstoraster) and is normally used
  to either test those filters or look at the data that is being sent to your
  raster printer driver.  RasterView is provided as free software under version 2
  of the GNU General Public license.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: rasterview-128.png

apps:
    rasterview:
        command: bin/rasterview
        desktop: usr/share/applications/Development/rasterview.desktop
        plugs: [home x11]

parts:
    main:
        plugin: autotools
        source: .

build-packages: [libfltk1.3-dev]

